// useless_conversion fires on code generated by #[pymethods] — not our code
#![allow(clippy::useless_conversion)]

use geo::{coord, Geometry, LineString, Point, Polygon, Rect};
use numpy::PyReadonlyArray1;
use pyo3::{exceptions::PyValueError, prelude::*, types::PyModule, Bound};

pub mod index;
pub mod planner;
pub mod query;
pub mod stats;

use index::{
    brute::BruteForce, grid::UniformGrid, kdtree::PackedKdTree, rtree::PackedRTree, SpatialIndex,
};
use planner::{cost::IndexKind, selector::select_index};
use query::{
    nearest::query_nearest,
    range::{query_contains, query_range},
    types::Query,
};
use stats::collector;

const MAX_BYTES: usize = 10 * 1024 * 1024 * 1024; // 10 GB hard cap

#[pyclass]
struct Engine {
    geometries: Vec<Geometry<f64>>,
    stats: stats::types::DatasetStats,
    brute: Option<BruteForce>,
    rtree: Option<PackedRTree>,
    kdtree: Option<PackedKdTree>,
    grid: Option<UniformGrid>,
}

impl Engine {
    fn build_index_if_needed(&mut self, kind: IndexKind) {
        match kind {
            IndexKind::BruteForce if self.brute.is_none() => {
                self.brute = Some(BruteForce::build(&self.geometries));
            }
            IndexKind::RTree if self.rtree.is_none() => {
                self.rtree = Some(PackedRTree::build(&self.geometries));
            }
            IndexKind::KdTree if self.kdtree.is_none() => {
                self.kdtree = Some(PackedKdTree::build(&self.geometries));
            }
            IndexKind::Grid if self.grid.is_none() => {
                self.grid = Some(UniformGrid::build(&self.geometries));
            }
            _ => {}
        }
    }
}

#[pymethods]
impl Engine {
    /// Construct from contiguous float64 numpy arrays of x and y coordinates.
    ///
    /// `xs` and `ys` are accessed as zero-copy `&[f64]` slices via NumPy's C API;
    /// no coordinate data is copied across the Python/Rust boundary.
    #[staticmethod]
    fn from_points(xs: PyReadonlyArray1<f64>, ys: PyReadonlyArray1<f64>) -> PyResult<Self> {
        let xs = xs.as_slice().map_err(|_| {
            PyValueError::new_err("xs must be a contiguous float64 array")
        })?;
        let ys = ys.as_slice().map_err(|_| {
            PyValueError::new_err("ys must be a contiguous float64 array")
        })?;
        if xs.len() != ys.len() {
            return Err(PyValueError::new_err("xs and ys must have the same length"));
        }
        let estimated_bytes = xs.len() * 64;
        if estimated_bytes > MAX_BYTES {
            return Err(PyValueError::new_err(format!(
                "Dataset too large: ~{} GB exceeds the 10 GB limit",
                estimated_bytes / (1024 * 1024 * 1024)
            )));
        }
        let geometries: Vec<Geometry<f64>> = xs
            .iter()
            .zip(ys.iter())
            .map(|(&x, &y)| Geometry::Point(Point::new(x, y)))
            .collect();
        let stats = collector::collect(&geometries);
        Ok(Engine {
            geometries,
            stats,
            brute: None,
            rtree: None,
            kdtree: None,
            grid: None,
        })
    }

    /// Construct from exterior ring coordinates of simple polygons.
    ///
    /// `offsets` has `n_polygons + 1` entries. Polygon `i` uses coordinates
    /// `xs[offsets[i]..offsets[i+1]]` and `ys[offsets[i]..offsets[i+1]]`.
    /// All three arrays are accessed as zero-copy slices via NumPy's C API.
    /// Only simple (non-holed) polygons are accepted; split MultiPolygons
    /// before calling this method.
    #[staticmethod]
    fn from_polygon_rings(
        xs: PyReadonlyArray1<f64>,
        ys: PyReadonlyArray1<f64>,
        offsets: PyReadonlyArray1<i64>,
    ) -> PyResult<Self> {
        let xs = xs.as_slice().map_err(|_| {
            PyValueError::new_err("xs must be a contiguous float64 array")
        })?;
        let ys = ys.as_slice().map_err(|_| {
            PyValueError::new_err("ys must be a contiguous float64 array")
        })?;
        let offsets = offsets.as_slice().map_err(|_| {
            PyValueError::new_err("offsets must be a contiguous int64 array")
        })?;
        if xs.len() != ys.len() {
            return Err(PyValueError::new_err("xs and ys must have the same length"));
        }
        if offsets.len() < 2 {
            return Err(PyValueError::new_err(
                "offsets must have at least 2 entries (one polygon requires two offset values)",
            ));
        }
        let estimated_bytes = xs.len() * 16;
        if estimated_bytes > MAX_BYTES {
            return Err(PyValueError::new_err(format!(
                "Dataset too large: ~{} GB exceeds the 10 GB limit",
                estimated_bytes / (1024 * 1024 * 1024)
            )));
        }
        let n = offsets.len() - 1;
        let mut geometries = Vec::with_capacity(n);
        for i in 0..n {
            let start = offsets[i] as usize;
            let end = offsets[i + 1] as usize;
            if end > xs.len() {
                return Err(PyValueError::new_err(format!(
                    "Offset out of bounds at polygon {i}: end={end} but coordinate count is {}",
                    xs.len()
                )));
            }
            let coords: Vec<geo::Coord<f64>> = (start..end)
                .map(|j| coord! { x: xs[j], y: ys[j] })
                .collect();
            geometries.push(Geometry::Polygon(Polygon::new(LineString::new(coords), vec![])));
        }
        let stats = collector::collect(&geometries);
        Ok(Engine {
            geometries,
            stats,
            brute: None,
            rtree: None,
            kdtree: None,
            grid: None,
        })
    }

    /// k-nearest-neighbour query
    fn knn(&mut self, x: f64, y: f64, k: usize, approximate: bool) -> PyResult<Vec<usize>> {
        let point = Point::new(x, y);
        let kind = select_index(
            &self.stats,
            &Query::Knn {
                point,
                k,
                approximate,
            },
        );
        self.build_index_if_needed(kind);

        let result = match kind {
            IndexKind::BruteForce => {
                query_nearest(self.brute.as_ref().unwrap(), &point, k, approximate)
            }
            IndexKind::RTree => query_nearest(self.rtree.as_ref().unwrap(), &point, k, approximate),
            IndexKind::KdTree => {
                query_nearest(self.kdtree.as_ref().unwrap(), &point, k, approximate)
            }
            IndexKind::Grid => query_nearest(self.grid.as_ref().unwrap(), &point, k, approximate),
        };
        Ok(result)
    }

    /// Bounding-box range query
    fn range_query(
        &mut self,
        min_x: f64,
        min_y: f64,
        max_x: f64,
        max_y: f64,
    ) -> PyResult<Vec<usize>> {
        let bbox = Rect::new(coord! { x: min_x, y: min_y }, coord! { x: max_x, y: max_y });
        let kind = select_index(&self.stats, &Query::Range { bbox });
        self.build_index_if_needed(kind);

        let result = match kind {
            IndexKind::BruteForce => {
                query_range(self.brute.as_ref().unwrap(), &bbox, &self.geometries)
            }
            IndexKind::RTree => query_range(self.rtree.as_ref().unwrap(), &bbox, &self.geometries),
            IndexKind::KdTree => {
                query_range(self.kdtree.as_ref().unwrap(), &bbox, &self.geometries)
            }
            IndexKind::Grid => query_range(self.grid.as_ref().unwrap(), &bbox, &self.geometries),
        };
        Ok(result)
    }

    /// Point-in-polygon contains query
    fn contains_query(&mut self, x: f64, y: f64) -> PyResult<Vec<usize>> {
        let point = Point::new(x, y);
        let kind = select_index(&self.stats, &Query::Contains { point });
        self.build_index_if_needed(kind);

        let result = match kind {
            IndexKind::BruteForce => {
                query_contains(self.brute.as_ref().unwrap(), &point, &self.geometries)
            }
            IndexKind::RTree => {
                query_contains(self.rtree.as_ref().unwrap(), &point, &self.geometries)
            }
            IndexKind::KdTree => {
                query_contains(self.kdtree.as_ref().unwrap(), &point, &self.geometries)
            }
            IndexKind::Grid => {
                query_contains(self.grid.as_ref().unwrap(), &point, &self.geometries)
            }
        };
        Ok(result)
    }

    fn __repr__(&self) -> String {
        format!(
            "Engine(n={}, kind={:?}, dist={:?})",
            self.stats.n, self.stats.kind, self.stats.distribution
        )
    }

    fn stats_info(&self) -> String {
        format!(
            "n={}, kind={:?}, distribution={:?}, density={:.3e}, extent={:?}",
            self.stats.n,
            self.stats.kind,
            self.stats.distribution,
            self.stats.mean_density,
            self.stats.extent,
        )
    }
}

#[pymodule]
fn _core(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<Engine>()?;
    Ok(())
}
