// useless_conversion fires on code generated by #[pymethods] — not our code
#![allow(clippy::useless_conversion)]

use std::sync::Arc;

use geo::{coord, Point, Rect};
use numpy::{PyArray1, PyReadonlyArray1};
use pyo3::{exceptions::PyValueError, prelude::*, types::PyModule, Bound};

pub mod index;
pub mod planner;
pub mod query;
pub mod stats;

use index::{
    brute::BruteForce, grid::UniformGrid, kdtree::PackedKdTree, rtree::PackedRTree, SpatialIndex,
};
use planner::{cost::IndexKind, selector::select_index};
use query::{
    batch::{
        par_bbox_filter, par_contains, par_knn, par_knn_with_delta, par_within_distance,
        par_within_distance_flipped,
    },
    nearest::query_nearest,
    range::{query_contains_polygons, query_range_points, query_range_polygons},
    types::Query,
};
use stats::{collector, types::GeometryKind};

#[pyclass]
struct Engine {
    xs: Arc<[f64]>,
    ys: Arc<[f64]>,
    /// None for point datasets; Some for polygon datasets.
    /// ring_offsets[r]..ring_offsets[r+1] gives ring r's coordinate range.
    ring_offsets: Option<Arc<[i64]>>,
    /// None for point datasets; Some for polygon datasets (always set alongside ring_offsets).
    /// poly_offsets[i]..poly_offsets[i+1] gives polygon i's ring range in ring_offsets.
    /// First ring per polygon is exterior; remaining rings are interior holes.
    poly_offsets: Option<Arc<[i64]>>,
    stats: stats::types::DatasetStats,
    brute: Option<BruteForce>,
    rtree: Option<PackedRTree>,
    kdtree: Option<PackedKdTree>,
    grid: Option<UniformGrid>,
    /// Delta buffer: points appended since last flush (point datasets only).
    /// Queries hit the main index + brute-force scan of delta.
    /// Flushed when accumulated brute-force scan cost exceeds index rebuild cost,
    /// or when delta exceeds DELTA_FLUSH_FRACTION of the main dataset (hard cap).
    delta_xs: Vec<f64>,
    delta_ys: Vec<f64>,
    /// Accumulated brute-force scan cost across all queries that touched the delta.
    /// Each query increments this by delta_xs.len(). Reset to 0 on flush.
    delta_query_cost: u64,
}

const DELTA_FLUSH_FRACTION: f64 = 0.1;

impl Engine {
    /// Merge the delta buffer into the main coordinate arrays and rebuild stats.
    /// Invalidates all indexes so the next query rebuilds against the full dataset.
    fn flush_delta(&mut self) {
        if self.delta_xs.is_empty() {
            return;
        }
        let mut new_xs = Vec::with_capacity(self.xs.len() + self.delta_xs.len());
        new_xs.extend_from_slice(&self.xs);
        new_xs.extend_from_slice(&self.delta_xs);

        let mut new_ys = Vec::with_capacity(self.ys.len() + self.delta_ys.len());
        new_ys.extend_from_slice(&self.ys);
        new_ys.extend_from_slice(&self.delta_ys);

        self.stats = collector::collect_points(&new_xs, &new_ys);
        self.xs = new_xs.into();
        self.ys = new_ys.into();
        self.delta_xs.clear();
        self.delta_ys.clear();
        self.delta_query_cost = 0;
        self.brute = None;
        self.rtree = None;
        self.kdtree = None;
        self.grid = None;
    }

    /// Brute-force scan the delta buffer for a range query.
    /// Returns indices offset by n_main so they address the unified index space.
    fn delta_range(&self, min_x: f64, min_y: f64, max_x: f64, max_y: f64) -> Vec<usize> {
        let n_main = self.xs.len();
        self.delta_xs
            .iter()
            .zip(self.delta_ys.iter())
            .enumerate()
            .filter_map(|(i, (&x, &y))| {
                if x >= min_x && x <= max_x && y >= min_y && y <= max_y {
                    Some(n_main + i)
                } else {
                    None
                }
            })
            .collect()
    }

    /// Flush if accumulated delta scan cost has exceeded the estimated index rebuild cost.
    /// Grid: O(N). KD-tree / R-tree: O(N log2 N). BruteForce: never trigger cost flush.
    fn maybe_flush_on_cost(&mut self, kind: IndexKind) {
        if self.delta_xs.is_empty() {
            return;
        }
        let n = self.xs.len() as u64;
        let threshold = match kind {
            IndexKind::BruteForce => return,
            IndexKind::Grid => n,
            IndexKind::KdTree | IndexKind::RTree => {
                if n <= 1 {
                    return;
                }
                n.saturating_mul((n as f64).log2().ceil() as u64)
            }
        };
        if self.delta_query_cost >= threshold {
            self.flush_delta();
        }
    }

    /// Merge main-index KNN results with delta candidates and return the top k by distance.
    fn merge_knn_with_delta(
        &self,
        main_results: Vec<usize>,
        x: f64,
        y: f64,
        k: usize,
    ) -> Vec<usize> {
        let n_main = self.xs.len();
        let mut candidates: Vec<(usize, f64)> = main_results
            .into_iter()
            .map(|i| {
                let dx = self.xs[i] - x;
                let dy = self.ys[i] - y;
                (i, dx * dx + dy * dy)
            })
            .collect();
        for (di, (&ex, &ey)) in self.delta_xs.iter().zip(self.delta_ys.iter()).enumerate() {
            let dx = ex - x;
            let dy = ey - y;
            candidates.push((n_main + di, dx * dx + dy * dy));
        }
        candidates
            .sort_unstable_by(|a, b| a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal));
        candidates.truncate(k);
        candidates.into_iter().map(|(i, _)| i).collect()
    }

    /// Two-pointer sorted-merge intersection of two sorted index slices.
    /// Both inputs must be sorted ascending. Returns indices present in both.
    fn sorted_intersect(a: Vec<usize>, b: Vec<usize>) -> Vec<usize> {
        let mut result = Vec::with_capacity(a.len().min(b.len()));
        let (mut i, mut j) = (0, 0);
        while i < a.len() && j < b.len() {
            match a[i].cmp(&b[j]) {
                std::cmp::Ordering::Equal => {
                    result.push(a[i]);
                    i += 1;
                    j += 1;
                }
                std::cmp::Ordering::Less => i += 1,
                std::cmp::Ordering::Greater => j += 1,
            }
        }
        result
    }

    fn build_index_if_needed(&mut self, kind: IndexKind) {
        match kind {
            IndexKind::BruteForce if self.brute.is_none() => {
                self.brute = Some(match self.ring_offsets.as_deref() {
                    Some(ring_off) => {
                        let poly_off = self.poly_offsets.as_deref().unwrap();
                        BruteForce::build_polygons(&self.xs, &self.ys, ring_off, poly_off)
                    }
                    None => BruteForce::build(Arc::clone(&self.xs), Arc::clone(&self.ys)),
                });
            }
            IndexKind::RTree if self.rtree.is_none() => {
                self.rtree = Some(match self.ring_offsets.as_deref() {
                    Some(ring_off) => {
                        let poly_off = self.poly_offsets.as_deref().unwrap();
                        PackedRTree::build_polygons(&self.xs, &self.ys, ring_off, poly_off)
                    }
                    None => PackedRTree::build(Arc::clone(&self.xs), Arc::clone(&self.ys)),
                });
            }
            IndexKind::KdTree if self.kdtree.is_none() => {
                let mut kd = PackedKdTree::build(Arc::clone(&self.xs), Arc::clone(&self.ys));
                kd.set_histogram(self.stats.histogram.clone());
                self.kdtree = Some(kd);
            }
            IndexKind::Grid if self.grid.is_none() => {
                self.grid = Some(UniformGrid::build(
                    Arc::clone(&self.xs),
                    Arc::clone(&self.ys),
                ));
            }
            _ => {}
        }
    }
}

#[pymethods]
impl Engine {
    /// Construct from contiguous float64 numpy arrays of x and y coordinates.
    ///
    /// Copies once from the numpy buffer into an Arc<[f64]>. All subsequent index
    /// builds share this allocation via Arc::clone — no further coordinate copying.
    #[staticmethod]
    fn from_points(xs: PyReadonlyArray1<f64>, ys: PyReadonlyArray1<f64>) -> PyResult<Self> {
        let xs_sl = xs
            .as_slice()
            .map_err(|_| PyValueError::new_err("xs must be a contiguous float64 array"))?;
        let ys_sl = ys
            .as_slice()
            .map_err(|_| PyValueError::new_err("ys must be a contiguous float64 array"))?;
        if xs_sl.len() != ys_sl.len() {
            return Err(PyValueError::new_err("xs and ys must have the same length"));
        }
        let stats = collector::collect_points(xs_sl, ys_sl);
        Ok(Engine {
            xs: xs_sl.into(),
            ys: ys_sl.into(),
            ring_offsets: None,
            poly_offsets: None,
            stats,
            brute: None,
            rtree: None,
            kdtree: None,
            grid: None,
            delta_xs: Vec::new(),
            delta_ys: Vec::new(),
            delta_query_cost: 0,
        })
    }

    /// Construct from two-level polygon ring arrays (supports holes).
    ///
    /// ring_offsets has total_rings + 1 entries; ring r uses coordinates
    /// xs[ring_offsets[r]..ring_offsets[r+1]].
    /// poly_offsets has n_polygons + 1 entries; polygon i uses rings
    /// poly_offsets[i]..poly_offsets[i+1]. The first ring is the exterior;
    /// any remaining rings are interior holes. MultiPolygons must be split
    /// before calling. Copies once from each numpy buffer into Arc<[_]>.
    #[staticmethod]
    fn from_polygon_rings(
        xs: PyReadonlyArray1<f64>,
        ys: PyReadonlyArray1<f64>,
        ring_offsets: PyReadonlyArray1<i64>,
        poly_offsets: PyReadonlyArray1<i64>,
    ) -> PyResult<Self> {
        let xs_sl = xs
            .as_slice()
            .map_err(|_| PyValueError::new_err("xs must be a contiguous float64 array"))?;
        let ys_sl = ys
            .as_slice()
            .map_err(|_| PyValueError::new_err("ys must be a contiguous float64 array"))?;
        let ring_sl = ring_offsets
            .as_slice()
            .map_err(|_| PyValueError::new_err("ring_offsets must be a contiguous int64 array"))?;
        let poly_sl = poly_offsets
            .as_slice()
            .map_err(|_| PyValueError::new_err("poly_offsets must be a contiguous int64 array"))?;
        if xs_sl.len() != ys_sl.len() {
            return Err(PyValueError::new_err("xs and ys must have the same length"));
        }
        if ring_sl.len() < 2 {
            return Err(PyValueError::new_err(
                "ring_offsets must have at least 2 entries",
            ));
        }
        if poly_sl.len() < 2 {
            return Err(PyValueError::new_err(
                "poly_offsets must have at least 2 entries (one polygon requires two values)",
            ));
        }
        let n_rings = ring_sl.len() - 1;
        for i in 0..n_rings {
            let end = ring_sl[i + 1] as usize;
            if end > xs_sl.len() {
                return Err(PyValueError::new_err(format!(
                    "ring_offsets out of bounds at ring {i}: end={end} but coordinate count is {}",
                    xs_sl.len()
                )));
            }
        }
        let n_polys = poly_sl.len() - 1;
        for i in 0..n_polys {
            let end = poly_sl[i + 1] as usize;
            if end > n_rings {
                return Err(PyValueError::new_err(format!(
                    "poly_offsets out of bounds at polygon {i}: end={end} but ring count is {n_rings}",
                )));
            }
        }
        let stats = collector::collect_polygons(xs_sl, ys_sl, ring_sl, poly_sl);
        Ok(Engine {
            xs: xs_sl.into(),
            ys: ys_sl.into(),
            ring_offsets: Some(ring_sl.into()),
            poly_offsets: Some(poly_sl.into()),
            stats,
            brute: None,
            rtree: None,
            kdtree: None,
            grid: None,
            delta_xs: Vec::new(),
            delta_ys: Vec::new(),
            delta_query_cost: 0,
        })
    }

    /// Build the optimal index for this dataset without issuing any query.
    ///
    /// Uses a representative range query to select and construct the index. Safe
    /// to call multiple times; no-op if the index is already built.
    fn build_index(&mut self) -> PyResult<()> {
        let kind = select_index(
            &self.stats,
            &Query::Range {
                bbox: Rect::new(coord! { x: 0.0, y: 0.0 }, coord! { x: 1.0, y: 1.0 }),
            },
        );
        self.build_index_if_needed(kind);
        Ok(())
    }

    /// k-nearest-neighbour query
    fn knn(&mut self, x: f64, y: f64, k: usize, approximate: bool) -> PyResult<Vec<usize>> {
        let kind = select_index(
            &self.stats,
            &Query::Knn {
                point: Point::new(x, y),
                k,
                approximate,
            },
        );
        self.build_index_if_needed(kind);
        let mut result = match kind {
            IndexKind::BruteForce => {
                query_nearest(self.brute.as_ref().unwrap(), x, y, k, approximate)
            }
            IndexKind::RTree => query_nearest(self.rtree.as_ref().unwrap(), x, y, k, approximate),
            IndexKind::KdTree => query_nearest(self.kdtree.as_ref().unwrap(), x, y, k, approximate),
            IndexKind::Grid => query_nearest(self.grid.as_ref().unwrap(), x, y, k, approximate),
        };
        if !self.delta_xs.is_empty() {
            result = self.merge_knn_with_delta(result, x, y, k);
            self.delta_query_cost += self.delta_xs.len() as u64;
            self.maybe_flush_on_cost(kind);
        }
        Ok(result)
    }

    /// Bounding-box range query
    fn range_query(
        &mut self,
        min_x: f64,
        min_y: f64,
        max_x: f64,
        max_y: f64,
    ) -> PyResult<Vec<usize>> {
        let bbox = Rect::new(coord! { x: min_x, y: min_y }, coord! { x: max_x, y: max_y });
        // Skip histogram early-exit when delta is non-empty: delta points are not in the histogram.
        if self.delta_xs.is_empty() && self.stats.kind == GeometryKind::Point {
            if let Some(hist) = &self.stats.histogram {
                if !hist.has_any_in_bbox(&bbox) {
                    return Ok(vec![]);
                }
            }
        }
        let kind = select_index(&self.stats, &Query::Range { bbox });
        self.build_index_if_needed(kind);

        let mut result = match (kind, self.ring_offsets.as_deref()) {
            (IndexKind::BruteForce, None) => {
                query_range_points(self.brute.as_ref().unwrap(), min_x, min_y, max_x, max_y)
            }
            (IndexKind::BruteForce, Some(ring_off)) => query_range_polygons(
                self.brute.as_ref().unwrap(),
                &self.xs,
                &self.ys,
                ring_off,
                self.poly_offsets.as_deref().unwrap(),
                min_x,
                min_y,
                max_x,
                max_y,
            ),
            (IndexKind::RTree, None) => {
                query_range_points(self.rtree.as_ref().unwrap(), min_x, min_y, max_x, max_y)
            }
            (IndexKind::RTree, Some(ring_off)) => query_range_polygons(
                self.rtree.as_ref().unwrap(),
                &self.xs,
                &self.ys,
                ring_off,
                self.poly_offsets.as_deref().unwrap(),
                min_x,
                min_y,
                max_x,
                max_y,
            ),
            (IndexKind::KdTree, None) => {
                query_range_points(self.kdtree.as_ref().unwrap(), min_x, min_y, max_x, max_y)
            }
            (IndexKind::KdTree, Some(ring_off)) => query_range_polygons(
                self.kdtree.as_ref().unwrap(),
                &self.xs,
                &self.ys,
                ring_off,
                self.poly_offsets.as_deref().unwrap(),
                min_x,
                min_y,
                max_x,
                max_y,
            ),
            (IndexKind::Grid, None) => {
                query_range_points(self.grid.as_ref().unwrap(), min_x, min_y, max_x, max_y)
            }
            (IndexKind::Grid, Some(ring_off)) => query_range_polygons(
                self.grid.as_ref().unwrap(),
                &self.xs,
                &self.ys,
                ring_off,
                self.poly_offsets.as_deref().unwrap(),
                min_x,
                min_y,
                max_x,
                max_y,
            ),
        };
        if !self.delta_xs.is_empty() {
            result.extend(self.delta_range(min_x, min_y, max_x, max_y));
            self.delta_query_cost += self.delta_xs.len() as u64;
            self.maybe_flush_on_cost(kind);
        }
        Ok(result)
    }

    /// Intersect multiple bounding-box queries using sorted merge on hit arrays.
    ///
    /// Runs each range query independently then intersects results via a two-pointer
    /// sorted merge. Operates in O(K * |H|) rather than O(K * N) bitmap AND passes,
    /// where |H| is the per-predicate hit count and K is the predicate count.
    /// Short-circuits when the running intersection becomes empty.
    fn intersect_ranges(&mut self, queries: Vec<(f64, f64, f64, f64)>) -> PyResult<Vec<usize>> {
        if queries.is_empty() {
            return Ok(vec![]);
        }
        let (min_x, min_y, max_x, max_y) = queries[0];
        let mut acc = self.range_query(min_x, min_y, max_x, max_y)?;
        acc.sort_unstable();
        for &(min_x, min_y, max_x, max_y) in &queries[1..] {
            if acc.is_empty() {
                return Ok(vec![]);
            }
            let mut hits = self.range_query(min_x, min_y, max_x, max_y)?;
            hits.sort_unstable();
            acc = Self::sorted_intersect(acc, hits);
        }
        Ok(acc)
    }

    /// k-nearest-neighbour query restricted to a candidate subset of the dataset.
    ///
    /// survivor_indices is a contiguous uint32 array of M row positions in the full
    /// dataset. Computes squared distances from (x, y) to each survivor directly
    /// from the coordinate arrays, then partial-sorts to find the k nearest.
    /// O(M + k log k) — exact, no index traversal, no oversampling.
    fn knn_from_candidates(
        &self,
        x: f64,
        y: f64,
        k: usize,
        survivor_indices: PyReadonlyArray1<u32>,
    ) -> PyResult<Vec<usize>> {
        let indices = survivor_indices.as_slice().map_err(|_| {
            PyValueError::new_err("survivor_indices must be a contiguous uint32 array")
        })?;
        if indices.is_empty() || k == 0 {
            return Ok(vec![]);
        }
        let k_actual = k.min(indices.len());

        let mut dist_idx: Vec<(f64, usize)> = indices
            .iter()
            .map(|&i| {
                let i = i as usize;
                let dx = self.xs[i] - x;
                let dy = self.ys[i] - y;
                (dx * dx + dy * dy, i)
            })
            .collect();

        // Partial sort: O(M) to place the k_actual-th element, O(k log k) to sort the top slice.
        dist_idx.select_nth_unstable_by(k_actual - 1, |a, b| {
            a.0.partial_cmp(&b.0).unwrap_or(std::cmp::Ordering::Equal)
        });
        dist_idx[..k_actual]
            .sort_unstable_by(|a, b| a.0.partial_cmp(&b.0).unwrap_or(std::cmp::Ordering::Equal));

        Ok(dist_idx[..k_actual].iter().map(|&(_, i)| i).collect())
    }

    /// Point-in-polygon contains query
    fn contains_query(&mut self, x: f64, y: f64) -> PyResult<Vec<usize>> {
        let point = Point::new(x, y);
        // Skip histogram early-exit when delta is non-empty: delta points are not in the histogram.
        if self.delta_xs.is_empty() && self.stats.kind == GeometryKind::Point {
            if let Some(hist) = &self.stats.histogram {
                if !hist.has_any_at(x, y) {
                    return Ok(vec![]);
                }
            }
        }
        let kind = select_index(&self.stats, &Query::Contains { point });
        self.build_index_if_needed(kind);

        let mut result = match (kind, self.ring_offsets.as_deref()) {
            (IndexKind::BruteForce, Some(ring_off)) => query_contains_polygons(
                self.brute.as_ref().unwrap(),
                &self.xs,
                &self.ys,
                ring_off,
                self.poly_offsets.as_deref().unwrap(),
                x,
                y,
            ),
            (IndexKind::RTree, Some(ring_off)) => query_contains_polygons(
                self.rtree.as_ref().unwrap(),
                &self.xs,
                &self.ys,
                ring_off,
                self.poly_offsets.as_deref().unwrap(),
                x,
                y,
            ),
            (IndexKind::KdTree, Some(ring_off)) => query_contains_polygons(
                self.kdtree.as_ref().unwrap(),
                &self.xs,
                &self.ys,
                ring_off,
                self.poly_offsets.as_deref().unwrap(),
                x,
                y,
            ),
            (IndexKind::Grid, Some(ring_off)) => query_contains_polygons(
                self.grid.as_ref().unwrap(),
                &self.xs,
                &self.ys,
                ring_off,
                self.poly_offsets.as_deref().unwrap(),
                x,
                y,
            ),
            // Point dataset: exact match within epsilon via degenerate range query.
            (IndexKind::BruteForce, None) => {
                let eps = f64::EPSILON * 1000.0;
                self.brute
                    .as_ref()
                    .unwrap()
                    .range(x - eps, y - eps, x + eps, y + eps)
            }
            (IndexKind::RTree, None) => {
                let eps = f64::EPSILON * 1000.0;
                self.rtree
                    .as_ref()
                    .unwrap()
                    .range(x - eps, y - eps, x + eps, y + eps)
            }
            (IndexKind::KdTree, None) => {
                let eps = f64::EPSILON * 1000.0;
                self.kdtree
                    .as_ref()
                    .unwrap()
                    .range(x - eps, y - eps, x + eps, y + eps)
            }
            (IndexKind::Grid, None) => {
                let eps = f64::EPSILON * 1000.0;
                self.grid
                    .as_ref()
                    .unwrap()
                    .range(x - eps, y - eps, x + eps, y + eps)
            }
        };
        // Delta scan for point datasets only (polygon datasets reject delta appends).
        if self.ring_offsets.is_none() && !self.delta_xs.is_empty() {
            let eps = f64::EPSILON * 1000.0;
            result.extend(self.delta_range(x - eps, y - eps, x + eps, y + eps));
            self.delta_query_cost += self.delta_xs.len() as u64;
            self.maybe_flush_on_cost(kind);
        }
        Ok(result)
    }

    /// Append new points to the delta buffer (point datasets only).
    ///
    /// Queries immediately reflect the new points via brute-force delta scan.
    /// The delta is automatically flushed into the main index when it exceeds
    /// DELTA_FLUSH_FRACTION of the main dataset size.
    fn append_delta(
        &mut self,
        xs: PyReadonlyArray1<f64>,
        ys: PyReadonlyArray1<f64>,
    ) -> PyResult<()> {
        if self.ring_offsets.is_some() {
            return Err(PyValueError::new_err(
                "delta buffer is not supported for polygon datasets",
            ));
        }
        let xs_sl = xs
            .as_slice()
            .map_err(|_| PyValueError::new_err("xs must be a contiguous float64 array"))?;
        let ys_sl = ys
            .as_slice()
            .map_err(|_| PyValueError::new_err("ys must be a contiguous float64 array"))?;
        if xs_sl.len() != ys_sl.len() {
            return Err(PyValueError::new_err("xs and ys must have the same length"));
        }
        self.delta_xs.extend_from_slice(xs_sl);
        self.delta_ys.extend_from_slice(ys_sl);

        let flush_threshold = (self.xs.len() as f64 * DELTA_FLUSH_FRACTION) as usize;
        if self.delta_xs.len() > flush_threshold.max(1) {
            self.flush_delta();
        }
        Ok(())
    }

    /// Force the delta buffer to be merged into the main index immediately.
    fn flush(&mut self) {
        self.flush_delta();
    }

    /// Number of points in the delta buffer (not yet flushed into the main index).
    fn delta_len(&self) -> usize {
        self.delta_xs.len()
    }

    /// For each query point, return the k nearest neighbours in the Engine's dataset.
    ///
    /// Crosses the Python/Rust boundary once; loops in Rust via rayon.
    /// Returns a flat array of shape `(n_queries * k,)`: block `i` holds the k
    /// result indices for query point `i`, sorted nearest-first.
    fn batch_knn_join<'py>(
        &mut self,
        py: Python<'py>,
        query_xs: PyReadonlyArray1<f64>,
        query_ys: PyReadonlyArray1<f64>,
        k: usize,
        approximate: bool,
    ) -> PyResult<Bound<'py, PyArray1<u64>>> {
        let qxs = query_xs
            .as_slice()
            .map_err(|_| PyValueError::new_err("query_xs must be a contiguous float64 array"))?;
        let qys = query_ys
            .as_slice()
            .map_err(|_| PyValueError::new_err("query_ys must be a contiguous float64 array"))?;
        if qxs.len() != qys.len() {
            return Err(PyValueError::new_err(
                "query_xs and query_ys must have the same length",
            ));
        }

        let kind = select_index(
            &self.stats,
            &Query::Knn {
                point: Point::new(0.0, 0.0),
                k,
                approximate,
            },
        );
        self.build_index_if_needed(kind);

        let results = if self.delta_xs.is_empty() {
            match kind {
                IndexKind::BruteForce => par_knn(self.brute.as_ref().unwrap(), qxs, qys, k),
                IndexKind::RTree => par_knn(self.rtree.as_ref().unwrap(), qxs, qys, k),
                IndexKind::KdTree => par_knn(self.kdtree.as_ref().unwrap(), qxs, qys, k),
                IndexKind::Grid => par_knn(self.grid.as_ref().unwrap(), qxs, qys, k),
            }
        } else {
            let out = match kind {
                IndexKind::BruteForce => par_knn_with_delta(
                    self.brute.as_ref().unwrap(),
                    qxs,
                    qys,
                    k,
                    &self.xs,
                    &self.ys,
                    &self.delta_xs,
                    &self.delta_ys,
                ),
                IndexKind::RTree => par_knn_with_delta(
                    self.rtree.as_ref().unwrap(),
                    qxs,
                    qys,
                    k,
                    &self.xs,
                    &self.ys,
                    &self.delta_xs,
                    &self.delta_ys,
                ),
                IndexKind::KdTree => par_knn_with_delta(
                    self.kdtree.as_ref().unwrap(),
                    qxs,
                    qys,
                    k,
                    &self.xs,
                    &self.ys,
                    &self.delta_xs,
                    &self.delta_ys,
                ),
                IndexKind::Grid => par_knn_with_delta(
                    self.grid.as_ref().unwrap(),
                    qxs,
                    qys,
                    k,
                    &self.xs,
                    &self.ys,
                    &self.delta_xs,
                    &self.delta_ys,
                ),
            };
            self.delta_query_cost += self.delta_xs.len() as u64 * qxs.len() as u64;
            self.maybe_flush_on_cost(kind);
            out
        };
        Ok(PyArray1::from_vec(py, results))
    }

    /// For each query point, return (query_idx, engine_idx) pairs for every engine
    /// point within `distance` of it (Euclidean). Point datasets only.
    ///
    /// `flipped`: when true, indexes the query points and iterates engine points instead.
    /// Produces identical results but is cheaper when len(query) << engine.n.
    ///
    /// Returns a flat u64 array of shape (M * 2,) interleaved [q0, e0, q1, e1, ...].
    fn batch_within_distance<'py>(
        &mut self,
        py: Python<'py>,
        query_xs: PyReadonlyArray1<f64>,
        query_ys: PyReadonlyArray1<f64>,
        distance: f64,
        flipped: bool,
    ) -> PyResult<Bound<'py, PyArray1<u64>>> {
        if self.ring_offsets.is_some() {
            return Err(PyValueError::new_err(
                "batch_within_distance requires a point dataset",
            ));
        }
        let qxs = query_xs
            .as_slice()
            .map_err(|_| PyValueError::new_err("query_xs must be a contiguous float64 array"))?;
        let qys = query_ys
            .as_slice()
            .map_err(|_| PyValueError::new_err("query_ys must be a contiguous float64 array"))?;
        if qxs.len() != qys.len() {
            return Err(PyValueError::new_err(
                "query_xs and query_ys must have the same length",
            ));
        }
        if flipped {
            let pairs = par_within_distance_flipped(qxs, qys, &self.xs, &self.ys, distance);
            return Ok(PyArray1::from_vec(py, pairs));
        }
        let kind = if self.stats.n < 500 {
            IndexKind::BruteForce
        } else {
            match self.stats.distribution {
                stats::types::Distribution::Uniform => IndexKind::Grid,
                _ => IndexKind::KdTree,
            }
        };
        self.build_index_if_needed(kind);
        let pairs = match kind {
            IndexKind::BruteForce => par_within_distance(
                self.brute.as_ref().unwrap(),
                qxs,
                qys,
                &self.xs,
                &self.ys,
                distance,
            ),
            IndexKind::RTree => par_within_distance(
                self.rtree.as_ref().unwrap(),
                qxs,
                qys,
                &self.xs,
                &self.ys,
                distance,
            ),
            IndexKind::KdTree => par_within_distance(
                self.kdtree.as_ref().unwrap(),
                qxs,
                qys,
                &self.xs,
                &self.ys,
                distance,
            ),
            IndexKind::Grid => par_within_distance(
                self.grid.as_ref().unwrap(),
                qxs,
                qys,
                &self.xs,
                &self.ys,
                distance,
            ),
        };
        Ok(PyArray1::from_vec(py, pairs))
    }

    /// For each query point, return its position in the query array if it falls
    /// within the given bounding box.
    ///
    /// Crosses the Python/Rust boundary once; filters in Rust via rayon.
    /// Returns indices (into the query arrays) of matching points, in order.
    #[allow(clippy::too_many_arguments)]
    fn batch_within<'py>(
        &self,
        py: Python<'py>,
        query_xs: PyReadonlyArray1<f64>,
        query_ys: PyReadonlyArray1<f64>,
        min_x: f64,
        min_y: f64,
        max_x: f64,
        max_y: f64,
    ) -> PyResult<Bound<'py, PyArray1<u64>>> {
        let qxs = query_xs
            .as_slice()
            .map_err(|_| PyValueError::new_err("query_xs must be a contiguous float64 array"))?;
        let qys = query_ys
            .as_slice()
            .map_err(|_| PyValueError::new_err("query_ys must be a contiguous float64 array"))?;
        if qxs.len() != qys.len() {
            return Err(PyValueError::new_err(
                "query_xs and query_ys must have the same length",
            ));
        }
        let results = par_bbox_filter(qxs, qys, min_x, min_y, max_x, max_y);
        Ok(PyArray1::from_vec(py, results))
    }

    /// For each query point, return (query_idx, engine_idx) pairs for every polygon
    /// in the Engine's dataset that contains that point.
    ///
    /// Crosses the Python/Rust boundary once; loops in Rust via rayon.
    /// Engine must be a polygon dataset. Returns a flat u64 array of shape (M * 2,)
    /// where M is the total number of (query, polygon) matches: pairs are interleaved
    /// [q0, e0, q1, e1, ...] for easy reshaping to (-1, 2) in Python.
    fn batch_contains<'py>(
        &mut self,
        py: Python<'py>,
        query_xs: PyReadonlyArray1<f64>,
        query_ys: PyReadonlyArray1<f64>,
    ) -> PyResult<Bound<'py, PyArray1<u64>>> {
        let qxs = query_xs
            .as_slice()
            .map_err(|_| PyValueError::new_err("query_xs must be a contiguous float64 array"))?;
        let qys = query_ys
            .as_slice()
            .map_err(|_| PyValueError::new_err("query_ys must be a contiguous float64 array"))?;
        if qxs.len() != qys.len() {
            return Err(PyValueError::new_err(
                "query_xs and query_ys must have the same length",
            ));
        }
        if self.ring_offsets.is_none() {
            return Err(PyValueError::new_err(
                "batch_contains requires a polygon dataset",
            ));
        }
        self.build_index_if_needed(IndexKind::RTree);
        let ring_off = self.ring_offsets.as_deref().unwrap();
        let poly_off = self.poly_offsets.as_deref().unwrap();
        let flat = par_contains(
            self.rtree.as_ref().unwrap(),
            qxs,
            qys,
            &self.xs,
            &self.ys,
            ring_off,
            poly_off,
        );
        Ok(PyArray1::from_vec(py, flat))
    }

    /// Number of geometries in the dataset
    fn n(&self) -> usize {
        self.stats.n
    }

    /// Bounding extent of the dataset as (min_x, min_y, max_x, max_y), or None if empty
    fn extent(&self) -> Option<(f64, f64, f64, f64)> {
        self.stats
            .extent
            .map(|r| (r.min().x, r.min().y, r.max().x, r.max().y))
    }

    fn __repr__(&self) -> String {
        format!(
            "Engine(n={}, kind={:?}, dist={:?})",
            self.stats.n, self.stats.kind, self.stats.distribution
        )
    }

    fn stats_info(&self) -> String {
        format!(
            "n={}, kind={:?}, distribution={:?}, density={:.3e}, extent={:?}",
            self.stats.n,
            self.stats.kind,
            self.stats.distribution,
            self.stats.mean_density,
            self.stats.extent,
        )
    }
}

#[pymodule]
fn _core(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<Engine>()?;
    Ok(())
}
