//! PyO3 entry point and public API surface for the PyCanopy spatial engine.

// useless_conversion fires on code generated by #[pymethods], not our code
#![allow(clippy::useless_conversion)]

use std::sync::Arc;

use geo::{coord, Point, Rect};
use numpy::{PyArray1, PyReadonlyArray1};
use pyo3::{exceptions::PyValueError, prelude::*, types::PyModule, Bound};

pub mod index;
pub mod planner;
pub mod query;
pub mod stats;
pub mod wkb;

use index::{
    brute::BruteForce, grid::UniformGrid, kdtree::PackedKdTree, rtree::PackedRTree, SpatialIndex,
};
use planner::{
    calibration::CostFactors,
    cost::{IndexKind, IndexMode},
    selector::{
        plan_access, plan_access_with_kind, point_distance_candidate, rtree_candidate, select_index,
    },
};
use query::{
    batch::{
        par_bbox_filter, par_contains, par_knn, par_knn_to_polygons, par_knn_to_polygons_sorted,
        par_knn_with_delta, par_points_within_distance_of_polygon, par_polygon_intersects_join,
        par_within_distance, par_within_distance_flipped, par_within_distance_to_polygons,
    },
    geometry::{convex_hull_area, polygon_area, polygon_intersection_area},
    multipoly::{dedup_indices, dedup_self_pairs, polygon_parts_csr, sum_part_areas},
    nearest::query_nearest,
    prepared::PreparedPolygons,
    range::{query_contains_polygons, query_range_points, query_range_polygons},
    types::Query,
};
use rayon::prelude::*;
use stats::{collector, types::GeometryKind};

#[pyclass]
struct Engine {
    xs: Arc<[f64]>,
    ys: Arc<[f64]>,
    /// None for point datasets.
    /// ring_offsets[r]..ring_offsets[r+1] gives the coord range of ring r.
    ring_offsets: Option<Arc<[i64]>>,
    /// poly_offsets[i]..poly_offsets[i+1] gives polygon i's ring range. First ring is exterior,
    /// remainder are holes. Set alongside ring_offsets.
    poly_offsets: Option<Arc<[i64]>>,
    stats: stats::types::DatasetStats,
    brute: Option<BruteForce>,
    rtree: Option<PackedRTree>,
    kdtree: Option<PackedKdTree>,
    grid: Option<UniformGrid>,
    /// Points appended since last flush, scanned alongside the main index on every query
    delta_xs: Vec<f64>,
    delta_ys: Vec<f64>,
    /// Accumulated delta-scan cost that drives the cost-based flush
    delta_query_cost: u64,
    /// Index build policy: Eager (default) / None / Auto
    index_mode: IndexMode,
    cost_factors: CostFactors,
    /// Sub-linear PIP edge index, built lazily on first containment join
    prepared_polys: Option<PreparedPolygons>,
    /// Maps each index part to its logical polygon, or None when no MultiPolygons exist
    part_poly: Option<Arc<[u32]>>,
    /// Count of logical polygons, equal to the part count when part_poly is None
    n_polygons: usize,
}

const DELTA_FLUSH_FRACTION: f64 = 0.1;

impl Engine {
    fn new_polygons(
        xs: Arc<[f64]>,
        ys: Arc<[f64]>,
        ring_offsets: Arc<[i64]>,
        poly_offsets: Arc<[i64]>,
        part_poly: Option<Arc<[u32]>>,
        n_polygons: usize,
    ) -> Engine {
        let stats = collector::collect_polygons(&xs, &ys, &ring_offsets, &poly_offsets);
        Engine {
            xs,
            ys,
            ring_offsets: Some(ring_offsets),
            poly_offsets: Some(poly_offsets),
            stats,
            brute: None,
            rtree: None,
            kdtree: None,
            grid: None,
            delta_xs: Vec::new(),
            delta_ys: Vec::new(),
            delta_query_cost: 0,
            index_mode: IndexMode::Eager,
            cost_factors: CostFactors::default(),
            prepared_polys: None,
            part_poly,
            n_polygons,
        }
    }

    fn flush_delta(&mut self) {
        // Clears all cached indexes so the next query rebuilds against the merged dataset
        if self.delta_xs.is_empty() {
            return;
        }
        let mut new_xs = Vec::with_capacity(self.xs.len() + self.delta_xs.len());
        new_xs.extend_from_slice(&self.xs);
        new_xs.extend_from_slice(&self.delta_xs);

        let mut new_ys = Vec::with_capacity(self.ys.len() + self.delta_ys.len());
        new_ys.extend_from_slice(&self.ys);
        new_ys.extend_from_slice(&self.delta_ys);

        self.stats = collector::collect_points(&new_xs, &new_ys);
        self.xs = new_xs.into();
        self.ys = new_ys.into();
        self.delta_xs.clear();
        self.delta_ys.clear();
        self.delta_query_cost = 0;
        self.brute = None;
        self.rtree = None;
        self.kdtree = None;
        self.grid = None;
    }

    fn delta_range(&self, min_x: f64, min_y: f64, max_x: f64, max_y: f64) -> Vec<usize> {
        // Indices are offset by xs.len() to address the combined xs/delta_xs space
        let n_main = self.xs.len();
        self.delta_xs
            .iter()
            .zip(self.delta_ys.iter())
            .enumerate()
            .filter_map(|(i, (&x, &y))| {
                if x >= min_x && x <= max_x && y >= min_y && y <= max_y {
                    Some(n_main + i)
                } else {
                    None
                }
            })
            .collect()
    }

    fn maybe_flush_on_cost(&mut self, kind: IndexKind) {
        if self.delta_xs.is_empty() {
            return;
        }
        let n = self.xs.len() as u64;
        let threshold = match kind {
            IndexKind::BruteForce => return,
            IndexKind::Grid => n,
            IndexKind::KdTree | IndexKind::RTree => {
                if n <= 1 {
                    return;
                }
                n.saturating_mul((n as f64).log2().ceil() as u64)
            }
        };
        if self.delta_query_cost >= threshold {
            self.flush_delta();
        }
    }

    fn merge_knn_with_delta(
        &self,
        main_results: Vec<usize>,
        x: f64,
        y: f64,
        k: usize,
    ) -> Vec<usize> {
        let n_main = self.xs.len();
        let mut candidates: Vec<(usize, f64)> = main_results
            .into_iter()
            .map(|i| {
                let dx = self.xs[i] - x;
                let dy = self.ys[i] - y;
                (i, dx * dx + dy * dy)
            })
            .collect();
        for (di, (&ex, &ey)) in self.delta_xs.iter().zip(self.delta_ys.iter()).enumerate() {
            let dx = ex - x;
            let dy = ey - y;
            candidates.push((n_main + di, dx * dx + dy * dy));
        }
        candidates
            .sort_unstable_by(|a, b| a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal));
        candidates.truncate(k);
        candidates.into_iter().map(|(i, _)| i).collect()
    }

    fn sorted_intersect(a: Vec<usize>, b: Vec<usize>) -> Vec<usize> {
        // Both inputs must be sorted ascending
        let mut result = Vec::with_capacity(a.len().min(b.len()));
        let (mut i, mut j) = (0, 0);
        while i < a.len() && j < b.len() {
            match a[i].cmp(&b[j]) {
                std::cmp::Ordering::Equal => {
                    result.push(a[i]);
                    i += 1;
                    j += 1;
                }
                std::cmp::Ordering::Less => i += 1,
                std::cmp::Ordering::Greater => j += 1,
            }
        }
        result
    }

    fn hits_to_mask(&self, hits: &[usize], candidates: &[u32]) -> Vec<bool> {
        let n_total = self.stats.n;
        let mut bitmap = vec![false; n_total];
        for &h in hits {
            if h < n_total {
                bitmap[h] = true;
            }
        }
        candidates
            .iter()
            .map(|&c| {
                let c = c as usize;
                c < n_total && bitmap[c]
            })
            .collect()
    }

    fn knn_indices_from_candidates(&self, x: f64, y: f64, k: usize, indices: &[u32]) -> Vec<usize> {
        if indices.is_empty() || k == 0 {
            return Vec::new();
        }
        let k_actual = k.min(indices.len());
        let mut dist_idx: Vec<(f64, usize)> = indices
            .iter()
            .map(|&i| {
                let i = i as usize;
                let dx = self.xs[i] - x;
                let dy = self.ys[i] - y;
                (dx * dx + dy * dy, i)
            })
            .collect();
        dist_idx.select_nth_unstable_by(k_actual - 1, |a, b| {
            a.0.partial_cmp(&b.0).unwrap_or(std::cmp::Ordering::Equal)
        });
        dist_idx[..k_actual]
            .sort_unstable_by(|a, b| a.0.partial_cmp(&b.0).unwrap_or(std::cmp::Ordering::Equal));
        dist_idx[..k_actual].iter().map(|&(_, i)| i).collect()
    }

    fn plan_index(&self, query: &Query, q_count: usize) -> IndexKind {
        plan_access(
            &self.stats,
            query,
            q_count,
            self.index_mode,
            &self.cost_factors,
        )
    }

    fn plan_index_kind(&self, query: &Query, q_count: usize, candidate: IndexKind) -> IndexKind {
        plan_access_with_kind(
            &self.stats,
            query,
            q_count,
            self.index_mode,
            &self.cost_factors,
            candidate,
        )
    }

    fn build_index_if_needed(&mut self, kind: IndexKind) {
        match kind {
            IndexKind::BruteForce if self.brute.is_none() => {
                self.brute = Some(match self.ring_offsets.as_deref() {
                    Some(ring_off) => {
                        let poly_off = self.poly_offsets.as_deref().unwrap();
                        BruteForce::build_polygons(&self.xs, &self.ys, ring_off, poly_off)
                    }
                    None => BruteForce::build(Arc::clone(&self.xs), Arc::clone(&self.ys)),
                });
            }
            IndexKind::RTree if self.rtree.is_none() => {
                self.rtree = Some(match self.ring_offsets.as_deref() {
                    Some(ring_off) => {
                        let poly_off = self.poly_offsets.as_deref().unwrap();
                        PackedRTree::build_polygons(&self.xs, &self.ys, ring_off, poly_off)
                    }
                    None => PackedRTree::build(Arc::clone(&self.xs), Arc::clone(&self.ys)),
                });
            }
            IndexKind::KdTree if self.kdtree.is_none() => {
                let mut kd = PackedKdTree::build(Arc::clone(&self.xs), Arc::clone(&self.ys));
                kd.set_histogram(self.stats.histogram.clone());
                self.kdtree = Some(kd);
            }
            IndexKind::Grid if self.grid.is_none() => {
                self.grid = Some(UniformGrid::build(
                    Arc::clone(&self.xs),
                    Arc::clone(&self.ys),
                ));
            }
            _ => {}
        }
    }

    fn build_prepared_if_needed(&mut self) {
        if self.index_mode == IndexMode::None || self.prepared_polys.is_some() {
            return;
        }
        if let (Some(ring), Some(poly)) =
            (self.ring_offsets.as_deref(), self.poly_offsets.as_deref())
        {
            self.prepared_polys = Some(PreparedPolygons::build(&self.xs, &self.ys, ring, poly));
        }
    }
}

#[pymethods]
impl Engine {
    /// Construct from contiguous float64 numpy arrays of x and y coordinates.
    /// Copies once into an Arc<[f64]> that all later index builds share via Arc::clone.
    #[staticmethod]
    fn from_points(xs: PyReadonlyArray1<f64>, ys: PyReadonlyArray1<f64>) -> PyResult<Self> {
        let xs_sl = xs
            .as_slice()
            .map_err(|_| PyValueError::new_err("xs must be a contiguous float64 array"))?;
        let ys_sl = ys
            .as_slice()
            .map_err(|_| PyValueError::new_err("ys must be a contiguous float64 array"))?;
        if xs_sl.len() != ys_sl.len() {
            return Err(PyValueError::new_err("xs and ys must have the same length"));
        }
        let stats = collector::collect_points(xs_sl, ys_sl);
        Ok(Engine {
            xs: xs_sl.into(),
            ys: ys_sl.into(),
            ring_offsets: None,
            poly_offsets: None,
            stats,
            brute: None,
            rtree: None,
            kdtree: None,
            grid: None,
            delta_xs: Vec::new(),
            delta_ys: Vec::new(),
            delta_query_cost: 0,
            index_mode: IndexMode::Eager,
            cost_factors: CostFactors::default(),
            prepared_polys: None,
            part_poly: None,
            n_polygons: 0,
        })
    }

    /// Construct from two-level polygon ring arrays (supports holes and MultiPolygons).
    ///
    /// ring_offsets and poly_offsets use the layout documented on the struct fields.
    /// part_poly maps each part to its logical polygon (None means one part per polygon).
    /// Copies once from each numpy buffer into Arc<[_]>.
    #[staticmethod]
    #[pyo3(signature = (xs, ys, ring_offsets, poly_offsets, part_poly=None))]
    fn from_polygon_rings(
        xs: PyReadonlyArray1<f64>,
        ys: PyReadonlyArray1<f64>,
        ring_offsets: PyReadonlyArray1<i64>,
        poly_offsets: PyReadonlyArray1<i64>,
        part_poly: Option<PyReadonlyArray1<i64>>,
    ) -> PyResult<Self> {
        let xs_sl = xs
            .as_slice()
            .map_err(|_| PyValueError::new_err("xs must be a contiguous float64 array"))?;
        let ys_sl = ys
            .as_slice()
            .map_err(|_| PyValueError::new_err("ys must be a contiguous float64 array"))?;
        let ring_sl = ring_offsets
            .as_slice()
            .map_err(|_| PyValueError::new_err("ring_offsets must be a contiguous int64 array"))?;
        let poly_sl = poly_offsets
            .as_slice()
            .map_err(|_| PyValueError::new_err("poly_offsets must be a contiguous int64 array"))?;
        if xs_sl.len() != ys_sl.len() {
            return Err(PyValueError::new_err("xs and ys must have the same length"));
        }
        if ring_sl.len() < 2 {
            return Err(PyValueError::new_err(
                "ring_offsets must have at least 2 entries",
            ));
        }
        if poly_sl.len() < 2 {
            return Err(PyValueError::new_err(
                "poly_offsets must have at least 2 entries (one polygon requires two values)",
            ));
        }
        let n_rings = ring_sl.len() - 1;
        for i in 0..n_rings {
            let end = ring_sl[i + 1] as usize;
            if end > xs_sl.len() {
                return Err(PyValueError::new_err(format!(
                    "ring_offsets out of bounds at ring {i}: end={end} but coordinate count is {}",
                    xs_sl.len()
                )));
            }
        }
        let n_polys = poly_sl.len() - 1;
        for i in 0..n_polys {
            let end = poly_sl[i + 1] as usize;
            if end > n_rings {
                return Err(PyValueError::new_err(format!(
                    "poly_offsets out of bounds at polygon {i}: end={end} but ring count is {n_rings}",
                )));
            }
        }
        // part_poly maps parts to logical polygons.
        // None means each part is its own logical polygon (no MultiPolygons).
        let (part_poly_arc, n_polygons): (Option<Arc<[u32]>>, usize) = match part_poly {
            Some(pp) => {
                let pp_sl = pp.as_slice().map_err(|_| {
                    PyValueError::new_err("part_poly must be a contiguous int64 array")
                })?;
                if pp_sl.len() != n_polys {
                    return Err(PyValueError::new_err(
                        "part_poly must have one entry per part (poly_offsets length minus one)",
                    ));
                }
                let n_logical = pp_sl.iter().copied().max().map_or(0, |m| m as usize + 1);
                (Some(pp_sl.iter().map(|&v| v as u32).collect()), n_logical)
            }
            None => (None, n_polys),
        };
        Ok(Engine::new_polygons(
            xs_sl.into(),
            ys_sl.into(),
            ring_sl.into(),
            poly_sl.into(),
            part_poly_arc,
            n_polygons,
        ))
    }

    /// Construct a polygon Engine directly from a WKB column, with no shapely roundtrip.
    ///
    /// Geometry i is data[offsets[i]..offsets[i+1]]. Decodes Polygon / MultiPolygon in one
    /// pass. Raises for any other WKB variant so the caller can fall back to shapely.
    #[staticmethod]
    fn from_wkb_polygons(
        data: PyReadonlyArray1<u8>,
        offsets: PyReadonlyArray1<i64>,
    ) -> PyResult<Self> {
        let data_sl = data
            .as_slice()
            .map_err(|_| PyValueError::new_err("data must be a contiguous uint8 array"))?;
        let off_sl = offsets
            .as_slice()
            .map_err(|_| PyValueError::new_err("offsets must be a contiguous int64 array"))?;
        let parsed = wkb::parse_polygons(data_sl, off_sl).map_err(PyValueError::new_err)?;
        let n_polygons = match &parsed.part_poly {
            Some(pp) => pp.iter().copied().max().map_or(0, |m| m as usize + 1),
            None => parsed.poly_offsets.len().saturating_sub(1),
        };
        Ok(Engine::new_polygons(
            parsed.xs.into(),
            parsed.ys.into(),
            parsed.ring_offsets.into(),
            parsed.poly_offsets.into(),
            parsed.part_poly.map(Arc::from),
            n_polygons,
        ))
    }

    /// Build the optimal index for this dataset without issuing any query, via a
    /// representative range query. Idempotent and a no-op if the index is already built.
    fn build_index(&mut self) -> PyResult<()> {
        let kind = select_index(
            &self.stats,
            &Query::Range {
                bbox: Rect::new(coord! { x: 0.0, y: 0.0 }, coord! { x: 1.0, y: 1.0 }),
            },
        );
        self.build_index_if_needed(kind);
        Ok(())
    }

    /// Set the index build policy ("auto" / "eager" / "none"), returning the previous
    /// mode as a string so callers can restore it after a scoped override.
    fn set_index_mode(&mut self, mode: &str) -> PyResult<String> {
        let new = match mode {
            "auto" => IndexMode::Auto,
            "eager" => IndexMode::Eager,
            "none" => IndexMode::None,
            other => {
                return Err(PyValueError::new_err(format!(
                    "index mode must be 'auto', 'eager', or 'none', got '{other}'"
                )))
            }
        };
        let prev = match self.index_mode {
            IndexMode::Auto => "auto",
            IndexMode::Eager => "eager",
            IndexMode::None => "none",
        };
        self.index_mode = new;
        Ok(prev.to_string())
    }

    /// Return the k dataset indices nearest to (x, y), sorted nearest-first
    fn knn(&mut self, x: f64, y: f64, k: usize) -> PyResult<Vec<usize>> {
        let kind = self.plan_index(
            &Query::Knn {
                point: Point::new(x, y),
                k,
            },
            1,
        );
        self.build_index_if_needed(kind);
        let mut result = match kind {
            IndexKind::BruteForce => query_nearest(self.brute.as_ref().unwrap(), x, y, k),
            IndexKind::RTree => query_nearest(self.rtree.as_ref().unwrap(), x, y, k),
            IndexKind::KdTree => query_nearest(self.kdtree.as_ref().unwrap(), x, y, k),
            IndexKind::Grid => query_nearest(self.grid.as_ref().unwrap(), x, y, k),
        };
        if !self.delta_xs.is_empty() {
            result = self.merge_knn_with_delta(result, x, y, k);
            self.delta_query_cost += self.delta_xs.len() as u64;
            self.maybe_flush_on_cost(kind);
        }
        Ok(result)
    }

    /// Dataset indices whose bounding boxes overlap [min_x, max_x] × [min_y, max_y]
    fn range_query(
        &mut self,
        min_x: f64,
        min_y: f64,
        max_x: f64,
        max_y: f64,
    ) -> PyResult<Vec<usize>> {
        let bbox = Rect::new(coord! { x: min_x, y: min_y }, coord! { x: max_x, y: max_y });
        // Skip histogram early-exit when delta is non-empty: delta points are not in the histogram
        if self.delta_xs.is_empty() && self.stats.kind == GeometryKind::Point {
            if let Some(hist) = &self.stats.histogram {
                if !hist.has_any_in_bbox(&bbox) {
                    return Ok(vec![]);
                }
            }
        }
        let kind = self.plan_index(&Query::Range { bbox }, 1);
        self.build_index_if_needed(kind);

        let mut result = match (kind, self.ring_offsets.as_deref()) {
            (IndexKind::BruteForce, None) => {
                query_range_points(self.brute.as_ref().unwrap(), min_x, min_y, max_x, max_y)
            }
            (IndexKind::BruteForce, Some(ring_off)) => query_range_polygons(
                self.brute.as_ref().unwrap(),
                &self.xs,
                &self.ys,
                ring_off,
                self.poly_offsets.as_deref().unwrap(),
                min_x,
                min_y,
                max_x,
                max_y,
            ),
            (IndexKind::RTree, None) => {
                query_range_points(self.rtree.as_ref().unwrap(), min_x, min_y, max_x, max_y)
            }
            (IndexKind::RTree, Some(ring_off)) => query_range_polygons(
                self.rtree.as_ref().unwrap(),
                &self.xs,
                &self.ys,
                ring_off,
                self.poly_offsets.as_deref().unwrap(),
                min_x,
                min_y,
                max_x,
                max_y,
            ),
            (IndexKind::KdTree, None) => {
                query_range_points(self.kdtree.as_ref().unwrap(), min_x, min_y, max_x, max_y)
            }
            (IndexKind::KdTree, Some(ring_off)) => query_range_polygons(
                self.kdtree.as_ref().unwrap(),
                &self.xs,
                &self.ys,
                ring_off,
                self.poly_offsets.as_deref().unwrap(),
                min_x,
                min_y,
                max_x,
                max_y,
            ),
            (IndexKind::Grid, None) => {
                query_range_points(self.grid.as_ref().unwrap(), min_x, min_y, max_x, max_y)
            }
            (IndexKind::Grid, Some(ring_off)) => query_range_polygons(
                self.grid.as_ref().unwrap(),
                &self.xs,
                &self.ys,
                ring_off,
                self.poly_offsets.as_deref().unwrap(),
                min_x,
                min_y,
                max_x,
                max_y,
            ),
        };
        if !self.delta_xs.is_empty() {
            result.extend(self.delta_range(min_x, min_y, max_x, max_y));
            self.delta_query_cost += self.delta_xs.len() as u64;
            self.maybe_flush_on_cost(kind);
        }
        if let Some(pp) = &self.part_poly {
            result = dedup_indices(result, pp);
        }
        Ok(result)
    }

    /// Intersect multiple bbox queries via two-pointer sorted merge on the hit arrays.
    /// O(K * |H|) over K predicates and per-predicate hit count |H| rather than O(K * N)
    /// bitmap ANDs. Short-circuits once the running intersection is empty.
    fn intersect_ranges(&mut self, queries: Vec<(f64, f64, f64, f64)>) -> PyResult<Vec<usize>> {
        if queries.is_empty() {
            return Ok(vec![]);
        }
        let (min_x, min_y, max_x, max_y) = queries[0];
        let mut acc = self.range_query(min_x, min_y, max_x, max_y)?;
        acc.sort_unstable();
        for &(min_x, min_y, max_x, max_y) in &queries[1..] {
            if acc.is_empty() {
                return Ok(vec![]);
            }
            let mut hits = self.range_query(min_x, min_y, max_x, max_y)?;
            hits.sort_unstable();
            acc = Self::sorted_intersect(acc, hits);
        }
        Ok(acc)
    }

    /// Intersect heterogeneous hit lists via iterative two-pointer sorted merge
    fn intersect_hits(&self, mut lists: Vec<Vec<usize>>) -> PyResult<Vec<usize>> {
        if lists.is_empty() {
            return Ok(vec![]);
        }
        lists.sort_by_key(|l| l.len());
        let mut acc = lists.swap_remove(0);
        acc.sort_unstable();
        for mut hits in lists {
            if acc.is_empty() {
                return Ok(vec![]);
            }
            hits.sort_unstable();
            acc = Self::sorted_intersect(acc, hits);
        }
        Ok(acc)
    }

    /// kNN restricted to a candidate subset. survivor_indices holds M uint32 row positions
    /// in the full dataset. Squared distance to each survivor then a partial sort for the
    /// top k. O(M + k log k) and exact with no index traversal.
    fn knn_from_candidates(
        &self,
        x: f64,
        y: f64,
        k: usize,
        survivor_indices: PyReadonlyArray1<u32>,
    ) -> PyResult<Vec<usize>> {
        let indices = survivor_indices.as_slice().map_err(|_| {
            PyValueError::new_err("survivor_indices must be a contiguous uint32 array")
        })?;
        Ok(self.knn_indices_from_candidates(x, y, k, indices))
    }

    /// Dataset polygon indices that contain the point (x, y)
    fn contains_query(&mut self, x: f64, y: f64) -> PyResult<Vec<usize>> {
        let point = Point::new(x, y);
        // Skip histogram early-exit when delta is non-empty: delta points are not in the histogram
        if self.delta_xs.is_empty() && self.stats.kind == GeometryKind::Point {
            if let Some(hist) = &self.stats.histogram {
                if !hist.has_any_at(x, y) {
                    return Ok(vec![]);
                }
            }
        }
        let kind = self.plan_index(&Query::Contains { point }, 1);
        self.build_index_if_needed(kind);

        let mut result = match (kind, self.ring_offsets.as_deref()) {
            (IndexKind::BruteForce, Some(ring_off)) => query_contains_polygons(
                self.brute.as_ref().unwrap(),
                &self.xs,
                &self.ys,
                ring_off,
                self.poly_offsets.as_deref().unwrap(),
                x,
                y,
            ),
            (IndexKind::RTree, Some(ring_off)) => query_contains_polygons(
                self.rtree.as_ref().unwrap(),
                &self.xs,
                &self.ys,
                ring_off,
                self.poly_offsets.as_deref().unwrap(),
                x,
                y,
            ),
            (IndexKind::KdTree, Some(ring_off)) => query_contains_polygons(
                self.kdtree.as_ref().unwrap(),
                &self.xs,
                &self.ys,
                ring_off,
                self.poly_offsets.as_deref().unwrap(),
                x,
                y,
            ),
            (IndexKind::Grid, Some(ring_off)) => query_contains_polygons(
                self.grid.as_ref().unwrap(),
                &self.xs,
                &self.ys,
                ring_off,
                self.poly_offsets.as_deref().unwrap(),
                x,
                y,
            ),
            // Point dataset: exact match within epsilon via degenerate range query
            (IndexKind::BruteForce, None) => {
                let eps = f64::EPSILON * 1000.0;
                self.brute
                    .as_ref()
                    .unwrap()
                    .range(x - eps, y - eps, x + eps, y + eps)
            }
            (IndexKind::RTree, None) => {
                let eps = f64::EPSILON * 1000.0;
                self.rtree
                    .as_ref()
                    .unwrap()
                    .range(x - eps, y - eps, x + eps, y + eps)
            }
            (IndexKind::KdTree, None) => {
                let eps = f64::EPSILON * 1000.0;
                self.kdtree
                    .as_ref()
                    .unwrap()
                    .range(x - eps, y - eps, x + eps, y + eps)
            }
            (IndexKind::Grid, None) => {
                let eps = f64::EPSILON * 1000.0;
                self.grid
                    .as_ref()
                    .unwrap()
                    .range(x - eps, y - eps, x + eps, y + eps)
            }
        };
        // Delta scan for point datasets only (polygon datasets reject delta appends)
        if self.ring_offsets.is_none() && !self.delta_xs.is_empty() {
            let eps = f64::EPSILON * 1000.0;
            result.extend(self.delta_range(x - eps, y - eps, x + eps, y + eps));
            self.delta_query_cost += self.delta_xs.len() as u64;
            self.maybe_flush_on_cost(kind);
        }
        if let Some(pp) = &self.part_poly {
            result = dedup_indices(result, pp);
        }
        Ok(result)
    }

    /// Boolean mask over `candidates` for a bounding-box filter, computed entirely in Rust
    fn range_mask<'py>(
        &mut self,
        py: Python<'py>,
        min_x: f64,
        min_y: f64,
        max_x: f64,
        max_y: f64,
        candidates: PyReadonlyArray1<u32>,
    ) -> PyResult<Bound<'py, PyArray1<bool>>> {
        let cand = candidates
            .as_slice()
            .map_err(|_| PyValueError::new_err("candidates must be a contiguous uint32 array"))?;
        let hits = self.range_query(min_x, min_y, max_x, max_y)?;
        Ok(PyArray1::from_vec(py, self.hits_to_mask(&hits, cand)))
    }

    /// Boolean mask over `candidates` for a point-in-polygon filter, computed entirely in Rust
    fn contains_mask<'py>(
        &mut self,
        py: Python<'py>,
        x: f64,
        y: f64,
        candidates: PyReadonlyArray1<u32>,
    ) -> PyResult<Bound<'py, PyArray1<bool>>> {
        let cand = candidates
            .as_slice()
            .map_err(|_| PyValueError::new_err("candidates must be a contiguous uint32 array"))?;
        let hits = self.contains_query(x, y)?;
        Ok(PyArray1::from_vec(py, self.hits_to_mask(&hits, cand)))
    }

    /// Boolean mask over `candidates` for fused range and contains predicates, intersected in Rust
    fn fused_mask<'py>(
        &mut self,
        py: Python<'py>,
        range_queries: Vec<(f64, f64, f64, f64)>,
        contains_points: Vec<(f64, f64)>,
        candidates: PyReadonlyArray1<u32>,
    ) -> PyResult<Bound<'py, PyArray1<bool>>> {
        let cand = candidates
            .as_slice()
            .map_err(|_| PyValueError::new_err("candidates must be a contiguous uint32 array"))?;
        let mut hit_lists: Vec<Vec<usize>> = Vec::new();
        if !range_queries.is_empty() {
            hit_lists.push(self.intersect_ranges(range_queries)?);
        }
        for (x, y) in contains_points {
            hit_lists.push(self.contains_query(x, y)?);
        }
        let hits = if hit_lists.is_empty() {
            Vec::new()
        } else {
            self.intersect_hits(hit_lists)?
        };
        Ok(PyArray1::from_vec(py, self.hits_to_mask(&hits, cand)))
    }

    /// Boolean mask over `candidates` for the k nearest among them, computed entirely in Rust
    fn knn_mask_from_candidates<'py>(
        &self,
        py: Python<'py>,
        x: f64,
        y: f64,
        k: usize,
        candidates: PyReadonlyArray1<u32>,
    ) -> PyResult<Bound<'py, PyArray1<bool>>> {
        let cand = candidates
            .as_slice()
            .map_err(|_| PyValueError::new_err("candidates must be a contiguous uint32 array"))?;
        let nearest = self.knn_indices_from_candidates(x, y, k, cand);
        Ok(PyArray1::from_vec(py, self.hits_to_mask(&nearest, cand)))
    }

    /// Append new points to the delta buffer (point datasets only). Queries reflect them
    /// immediately via the delta scan. Auto-flushed past DELTA_FLUSH_FRACTION of the main.
    fn append_delta(
        &mut self,
        xs: PyReadonlyArray1<f64>,
        ys: PyReadonlyArray1<f64>,
    ) -> PyResult<()> {
        if self.ring_offsets.is_some() {
            return Err(PyValueError::new_err(
                "delta buffer is not supported for polygon datasets",
            ));
        }
        let xs_sl = xs
            .as_slice()
            .map_err(|_| PyValueError::new_err("xs must be a contiguous float64 array"))?;
        let ys_sl = ys
            .as_slice()
            .map_err(|_| PyValueError::new_err("ys must be a contiguous float64 array"))?;
        if xs_sl.len() != ys_sl.len() {
            return Err(PyValueError::new_err("xs and ys must have the same length"));
        }
        self.delta_xs.extend_from_slice(xs_sl);
        self.delta_ys.extend_from_slice(ys_sl);

        let flush_threshold = (self.xs.len() as f64 * DELTA_FLUSH_FRACTION) as usize;
        if self.delta_xs.len() > flush_threshold.max(1) {
            self.flush_delta();
        }
        Ok(())
    }

    /// Force the delta buffer to be merged into the main index immediately
    fn flush(&mut self) {
        self.flush_delta();
    }

    /// Number of points in the delta buffer (not yet flushed into the main index)
    fn delta_len(&self) -> usize {
        self.delta_xs.len()
    }

    /// For each query point, return its k nearest neighbours in the Engine's dataset,
    /// nearest-first.
    fn batch_knn_join<'py>(
        &mut self,
        py: Python<'py>,
        query_xs: PyReadonlyArray1<f64>,
        query_ys: PyReadonlyArray1<f64>,
        k: usize,
    ) -> PyResult<Bound<'py, PyArray1<u64>>> {
        let qxs = query_xs
            .as_slice()
            .map_err(|_| PyValueError::new_err("query_xs must be a contiguous float64 array"))?;
        let qys = query_ys
            .as_slice()
            .map_err(|_| PyValueError::new_err("query_ys must be a contiguous float64 array"))?;
        if qxs.len() != qys.len() {
            return Err(PyValueError::new_err(
                "query_xs and query_ys must have the same length",
            ));
        }

        let kind = self.plan_index(
            &Query::Knn {
                point: Point::new(0.0, 0.0),
                k,
            },
            qxs.len(),
        );
        self.build_index_if_needed(kind);

        let results = if self.delta_xs.is_empty() {
            match kind {
                IndexKind::BruteForce => par_knn(self.brute.as_ref().unwrap(), qxs, qys, k),
                IndexKind::RTree => par_knn(self.rtree.as_ref().unwrap(), qxs, qys, k),
                IndexKind::KdTree => par_knn(self.kdtree.as_ref().unwrap(), qxs, qys, k),
                IndexKind::Grid => par_knn(self.grid.as_ref().unwrap(), qxs, qys, k),
            }
        } else {
            let out = match kind {
                IndexKind::BruteForce => par_knn_with_delta(
                    self.brute.as_ref().unwrap(),
                    qxs,
                    qys,
                    k,
                    &self.xs,
                    &self.ys,
                    &self.delta_xs,
                    &self.delta_ys,
                ),
                IndexKind::RTree => par_knn_with_delta(
                    self.rtree.as_ref().unwrap(),
                    qxs,
                    qys,
                    k,
                    &self.xs,
                    &self.ys,
                    &self.delta_xs,
                    &self.delta_ys,
                ),
                IndexKind::KdTree => par_knn_with_delta(
                    self.kdtree.as_ref().unwrap(),
                    qxs,
                    qys,
                    k,
                    &self.xs,
                    &self.ys,
                    &self.delta_xs,
                    &self.delta_ys,
                ),
                IndexKind::Grid => par_knn_with_delta(
                    self.grid.as_ref().unwrap(),
                    qxs,
                    qys,
                    k,
                    &self.xs,
                    &self.ys,
                    &self.delta_xs,
                    &self.delta_ys,
                ),
            };
            self.delta_query_cost += self.delta_xs.len() as u64 * qxs.len() as u64;
            self.maybe_flush_on_cost(kind);
            out
        };
        Ok(PyArray1::from_vec(py, results))
    }

    /// For each query point, return (query_idx, engine_idx) pairs for every engine point
    /// within `distance` (Euclidean). Point datasets only.
    ///
    /// `flipped` indexes the query side and iterates engine points instead. Same results
    /// and cheaper when len(query) >> engine.n.
    fn batch_within_distance<'py>(
        &mut self,
        py: Python<'py>,
        query_xs: PyReadonlyArray1<f64>,
        query_ys: PyReadonlyArray1<f64>,
        distance: f64,
        flipped: bool,
    ) -> PyResult<Bound<'py, PyArray1<u64>>> {
        if self.ring_offsets.is_some() {
            return Err(PyValueError::new_err(
                "batch_within_distance requires a point dataset",
            ));
        }
        let qxs = query_xs
            .as_slice()
            .map_err(|_| PyValueError::new_err("query_xs must be a contiguous float64 array"))?;
        let qys = query_ys
            .as_slice()
            .map_err(|_| PyValueError::new_err("query_ys must be a contiguous float64 array"))?;
        if qxs.len() != qys.len() {
            return Err(PyValueError::new_err(
                "query_xs and query_ys must have the same length",
            ));
        }
        if flipped {
            let pairs = par_within_distance_flipped(qxs, qys, &self.xs, &self.ys, distance);
            return Ok(PyArray1::from_vec(py, pairs));
        }
        let candidate = point_distance_candidate(&self.stats);
        let bbox = Rect::new(
            coord! { x: 0.0, y: 0.0 },
            coord! { x: 2.0 * distance, y: 2.0 * distance },
        );
        let kind = self.plan_index_kind(&Query::Range { bbox }, qxs.len(), candidate);
        self.build_index_if_needed(kind);
        let pairs = match kind {
            IndexKind::BruteForce => par_within_distance(
                self.brute.as_ref().unwrap(),
                qxs,
                qys,
                &self.xs,
                &self.ys,
                distance,
            ),
            IndexKind::RTree => par_within_distance(
                self.rtree.as_ref().unwrap(),
                qxs,
                qys,
                &self.xs,
                &self.ys,
                distance,
            ),
            IndexKind::KdTree => par_within_distance(
                self.kdtree.as_ref().unwrap(),
                qxs,
                qys,
                &self.xs,
                &self.ys,
                distance,
            ),
            IndexKind::Grid => par_within_distance(
                self.grid.as_ref().unwrap(),
                qxs,
                qys,
                &self.xs,
                &self.ys,
                distance,
            ),
        };
        Ok(PyArray1::from_vec(py, pairs))
    }

    /// Return the query-array positions of the points within the bounding box in order
    #[allow(clippy::too_many_arguments)]
    fn batch_within<'py>(
        &self,
        py: Python<'py>,
        query_xs: PyReadonlyArray1<f64>,
        query_ys: PyReadonlyArray1<f64>,
        min_x: f64,
        min_y: f64,
        max_x: f64,
        max_y: f64,
    ) -> PyResult<Bound<'py, PyArray1<u64>>> {
        let qxs = query_xs
            .as_slice()
            .map_err(|_| PyValueError::new_err("query_xs must be a contiguous float64 array"))?;
        let qys = query_ys
            .as_slice()
            .map_err(|_| PyValueError::new_err("query_ys must be a contiguous float64 array"))?;
        if qxs.len() != qys.len() {
            return Err(PyValueError::new_err(
                "query_xs and query_ys must have the same length",
            ));
        }
        let results = par_bbox_filter(qxs, qys, min_x, min_y, max_x, max_y);
        Ok(PyArray1::from_vec(py, results))
    }

    /// For each query point, return (query_idx, engine_idx) pairs for every polygon that
    /// contains it. Polygon dataset only.
    fn batch_contains<'py>(
        &mut self,
        py: Python<'py>,
        query_xs: PyReadonlyArray1<f64>,
        query_ys: PyReadonlyArray1<f64>,
    ) -> PyResult<Bound<'py, PyArray1<u64>>> {
        let qxs = query_xs
            .as_slice()
            .map_err(|_| PyValueError::new_err("query_xs must be a contiguous float64 array"))?;
        let qys = query_ys
            .as_slice()
            .map_err(|_| PyValueError::new_err("query_ys must be a contiguous float64 array"))?;
        if qxs.len() != qys.len() {
            return Err(PyValueError::new_err(
                "query_xs and query_ys must have the same length",
            ));
        }
        if self.ring_offsets.is_none() {
            return Err(PyValueError::new_err(
                "batch_contains requires a polygon dataset",
            ));
        }
        let kind = self.plan_index_kind(
            &Query::Contains {
                point: Point::new(0.0, 0.0),
            },
            qxs.len(),
            IndexKind::RTree,
        );
        self.build_index_if_needed(kind);
        self.build_prepared_if_needed();
        let ring_off = self.ring_offsets.as_deref().unwrap();
        let poly_off = self.poly_offsets.as_deref().unwrap();
        let prepared = self.prepared_polys.as_ref();
        let part_poly = self.part_poly.as_deref();
        let flat = match kind {
            IndexKind::BruteForce => par_contains(
                self.brute.as_ref().unwrap(),
                qxs,
                qys,
                &self.xs,
                &self.ys,
                ring_off,
                poly_off,
                prepared,
                part_poly,
            ),
            _ => par_contains(
                self.rtree.as_ref().unwrap(),
                qxs,
                qys,
                &self.xs,
                &self.ys,
                ring_off,
                poly_off,
                prepared,
                part_poly,
            ),
        };
        Ok(PyArray1::from_vec(py, flat))
    }

    /// For each query point, return (query_idx, polygon_idx) pairs for every Engine
    /// polygon within `distance` of it. Engine must be a polygon dataset.
    ///
    /// Returns a flat u64 array interleaved [q0, e0, q1, e1, ...] for reshaping to (-1, 2).
    fn batch_within_distance_to_polygons<'py>(
        &mut self,
        py: Python<'py>,
        query_xs: PyReadonlyArray1<f64>,
        query_ys: PyReadonlyArray1<f64>,
        distance: f64,
    ) -> PyResult<Bound<'py, PyArray1<u64>>> {
        let qxs = query_xs
            .as_slice()
            .map_err(|_| PyValueError::new_err("query_xs must be a contiguous float64 array"))?;
        let qys = query_ys
            .as_slice()
            .map_err(|_| PyValueError::new_err("query_ys must be a contiguous float64 array"))?;
        if qxs.len() != qys.len() {
            return Err(PyValueError::new_err(
                "query_xs and query_ys must have the same length",
            ));
        }
        if self.ring_offsets.is_none() {
            return Err(PyValueError::new_err(
                "batch_within_distance_to_polygons requires a polygon dataset",
            ));
        }
        let bbox = Rect::new(
            coord! { x: 0.0, y: 0.0 },
            coord! { x: 2.0 * distance, y: 2.0 * distance },
        );
        let kind = self.plan_index_kind(&Query::Range { bbox }, qxs.len(), IndexKind::RTree);
        self.build_index_if_needed(kind);
        let ring_off = self.ring_offsets.as_deref().unwrap();
        let poly_off = self.poly_offsets.as_deref().unwrap();
        let part_poly = self.part_poly.as_deref();
        let flat = match kind {
            IndexKind::BruteForce => par_within_distance_to_polygons(
                self.brute.as_ref().unwrap(),
                qxs,
                qys,
                &self.xs,
                &self.ys,
                ring_off,
                poly_off,
                distance,
                part_poly,
            ),
            _ => par_within_distance_to_polygons(
                self.rtree.as_ref().unwrap(),
                qxs,
                qys,
                &self.xs,
                &self.ys,
                ring_off,
                poly_off,
                distance,
                part_poly,
            ),
        };
        Ok(PyArray1::from_vec(py, flat))
    }

    /// For each query point, return the k nearest Engine polygons by exact
    /// point-to-polygon distance. Engine must be a polygon dataset.
    ///
    /// Returns (engine_indices, distances), each a flat array of shape (n_queries * k,)
    /// in per-query blocks. Padding slots (fewer than k candidates) use u64::MAX and inf.
    #[allow(clippy::type_complexity)]
    fn batch_knn_to_polygons<'py>(
        &mut self,
        py: Python<'py>,
        query_xs: PyReadonlyArray1<f64>,
        query_ys: PyReadonlyArray1<f64>,
        k: usize,
    ) -> PyResult<(Bound<'py, PyArray1<u64>>, Bound<'py, PyArray1<f64>>)> {
        let qxs = query_xs
            .as_slice()
            .map_err(|_| PyValueError::new_err("query_xs must be a contiguous float64 array"))?;
        let qys = query_ys
            .as_slice()
            .map_err(|_| PyValueError::new_err("query_ys must be a contiguous float64 array"))?;
        if qxs.len() != qys.len() {
            return Err(PyValueError::new_err(
                "query_xs and query_ys must have the same length",
            ));
        }
        if self.ring_offsets.is_none() {
            return Err(PyValueError::new_err(
                "batch_knn_to_polygons requires a polygon dataset",
            ));
        }
        let kind = self.plan_index_kind(
            &Query::Knn {
                point: Point::new(0.0, 0.0),
                k,
            },
            qxs.len(),
            IndexKind::RTree,
        );
        self.build_index_if_needed(kind);
        let ring_off = self.ring_offsets.as_deref().unwrap();
        let poly_off = self.poly_offsets.as_deref().unwrap();
        let n_parts = poly_off.len().saturating_sub(1);
        let part_poly = self.part_poly.as_deref();
        let (idx, dist) = match kind {
            IndexKind::BruteForce => par_knn_to_polygons(
                self.brute.as_ref().unwrap(),
                qxs,
                qys,
                &self.xs,
                &self.ys,
                ring_off,
                poly_off,
                k,
                n_parts,
                part_poly,
            ),
            _ => par_knn_to_polygons(
                self.rtree.as_ref().unwrap(),
                qxs,
                qys,
                &self.xs,
                &self.ys,
                ring_off,
                poly_off,
                k,
                n_parts,
                part_poly,
            ),
        };
        Ok((PyArray1::from_vec(py, idx), PyArray1::from_vec(py, dist)))
    }

    /// Like `batch_knn_to_polygons` but returns all valid pairs globally sorted by
    /// (distance ASC, target_idx ASC). No per-query blocks, no padding slots.
    ///
    /// Returns `(query_indices, target_indices, distances)` as three flat arrays. The sort
    /// happens inside Rust via rayon, so no Polars streaming sort or EBS spill is needed.
    /// Engine must be a polygon dataset.
    #[allow(clippy::type_complexity)]
    fn batch_knn_to_polygons_sorted<'py>(
        &mut self,
        py: Python<'py>,
        query_xs: PyReadonlyArray1<f64>,
        query_ys: PyReadonlyArray1<f64>,
        k: usize,
    ) -> PyResult<(
        Bound<'py, PyArray1<u64>>,
        Bound<'py, PyArray1<u64>>,
        Bound<'py, PyArray1<f64>>,
    )> {
        let qxs = query_xs
            .as_slice()
            .map_err(|_| PyValueError::new_err("query_xs must be a contiguous float64 array"))?;
        let qys = query_ys
            .as_slice()
            .map_err(|_| PyValueError::new_err("query_ys must be a contiguous float64 array"))?;
        if qxs.len() != qys.len() {
            return Err(PyValueError::new_err(
                "query_xs and query_ys must have the same length",
            ));
        }
        if self.ring_offsets.is_none() {
            return Err(PyValueError::new_err(
                "batch_knn_to_polygons_sorted requires a polygon dataset",
            ));
        }
        let kind = self.plan_index_kind(
            &Query::Knn {
                point: Point::new(0.0, 0.0),
                k,
            },
            qxs.len(),
            IndexKind::RTree,
        );
        self.build_index_if_needed(kind);
        let ring_off = self.ring_offsets.as_deref().unwrap();
        let poly_off = self.poly_offsets.as_deref().unwrap();
        let n_parts = poly_off.len().saturating_sub(1);
        let part_poly = self.part_poly.as_deref();
        let (q_idx, t_idx, dist) = match kind {
            IndexKind::BruteForce => par_knn_to_polygons_sorted(
                self.brute.as_ref().unwrap(),
                qxs,
                qys,
                &self.xs,
                &self.ys,
                ring_off,
                poly_off,
                k,
                n_parts,
                part_poly,
            ),
            _ => par_knn_to_polygons_sorted(
                self.rtree.as_ref().unwrap(),
                qxs,
                qys,
                &self.xs,
                &self.ys,
                ring_off,
                poly_off,
                k,
                n_parts,
                part_poly,
            ),
        };
        Ok((
            PyArray1::from_vec(py, q_idx),
            PyArray1::from_vec(py, t_idx),
            PyArray1::from_vec(py, dist),
        ))
    }

    /// Self-join: unordered pairs (i, j) with i < j of Engine polygons that intersect.
    /// Engine must be a polygon dataset.
    ///
    /// Returns a flat u64 array interleaved [i0, j0, i1, j1, ...] for reshaping to (-1, 2).
    fn polygon_intersects_self_join<'py>(
        &mut self,
        py: Python<'py>,
    ) -> PyResult<Bound<'py, PyArray1<u64>>> {
        if self.ring_offsets.is_none() {
            return Err(PyValueError::new_err(
                "polygon_intersects_self_join requires a polygon dataset",
            ));
        }
        let kind = self.plan_index_kind(
            &Query::Contains {
                point: Point::new(0.0, 0.0),
            },
            self.stats.n,
            IndexKind::RTree,
        );
        self.build_index_if_needed(kind);
        let ring_off = self.ring_offsets.as_deref().unwrap();
        let poly_off = self.poly_offsets.as_deref().unwrap();
        let flat = match kind {
            IndexKind::BruteForce => par_polygon_intersects_join(
                self.brute.as_ref().unwrap(),
                &self.xs,
                &self.ys,
                ring_off,
                poly_off,
            ),
            _ => par_polygon_intersects_join(
                self.rtree.as_ref().unwrap(),
                &self.xs,
                &self.ys,
                ring_off,
                poly_off,
            ),
        };
        let flat = match &self.part_poly {
            Some(pp) => dedup_self_pairs(flat, pp),
            None => flat,
        };
        Ok(PyArray1::from_vec(py, flat))
    }

    /// Unsigned area of every Engine polygon, in dataset order. Polygon datasets only.
    /// A MultiPolygon's area is the sum of its parts.
    fn polygon_areas<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyArray1<f64>>> {
        if self.ring_offsets.is_none() {
            return Err(PyValueError::new_err(
                "polygon_areas requires a polygon dataset",
            ));
        }
        let ring_off = self.ring_offsets.as_deref().unwrap();
        let poly_off = self.poly_offsets.as_deref().unwrap();
        let n_parts = poly_off.len().saturating_sub(1);
        let part_areas: Vec<f64> = (0..n_parts)
            .into_par_iter()
            .map(|i| polygon_area(&self.xs, &self.ys, ring_off, poly_off, i))
            .collect();
        let areas = match &self.part_poly {
            Some(pp) => sum_part_areas(&part_areas, pp, self.n_polygons),
            None => part_areas,
        };
        Ok(PyArray1::from_vec(py, areas))
    }

    /// Unsigned intersection area for each (i, j) pair of Engine polygons.
    /// `i_idx` and `j_idx` must have equal length. Polygon datasets only.
    fn polygon_pairs_intersection_area<'py>(
        &self,
        py: Python<'py>,
        i_idx: PyReadonlyArray1<u64>,
        j_idx: PyReadonlyArray1<u64>,
    ) -> PyResult<Bound<'py, PyArray1<f64>>> {
        if self.ring_offsets.is_none() {
            return Err(PyValueError::new_err(
                "polygon_pairs_intersection_area requires a polygon dataset",
            ));
        }
        let is = i_idx
            .as_slice()
            .map_err(|_| PyValueError::new_err("i_idx must be a contiguous uint64 array"))?;
        let js = j_idx
            .as_slice()
            .map_err(|_| PyValueError::new_err("j_idx must be a contiguous uint64 array"))?;
        if is.len() != js.len() {
            return Err(PyValueError::new_err(
                "i_idx and j_idx must have the same length",
            ));
        }
        let ring_off = self.ring_offsets.as_deref().unwrap();
        let poly_off = self.poly_offsets.as_deref().unwrap();
        // For MultiPolygons the pair area is the sum over their part pairs: parts within
        // one polygon are disjoint, so the part intersections partition the overlap.
        let areas: Vec<f64> = match &self.part_poly {
            Some(pp) => {
                let (offsets, parts) = polygon_parts_csr(pp, self.n_polygons);
                let parts_of = |g: usize| &parts[offsets[g] as usize..offsets[g + 1] as usize];
                is.par_iter()
                    .zip(js.par_iter())
                    .map(|(&i, &j)| {
                        let mut area = 0.0;
                        for &pi in parts_of(i as usize) {
                            for &pj in parts_of(j as usize) {
                                area += polygon_intersection_area(
                                    &self.xs,
                                    &self.ys,
                                    ring_off,
                                    poly_off,
                                    pi as usize,
                                    pj as usize,
                                );
                            }
                        }
                        area
                    })
                    .collect()
            }
            None => is
                .par_iter()
                .zip(js.par_iter())
                .map(|(&i, &j)| {
                    polygon_intersection_area(
                        &self.xs, &self.ys, ring_off, poly_off, i as usize, j as usize,
                    )
                })
                .collect(),
        };
        Ok(PyArray1::from_vec(py, areas))
    }

    /// Indices of Engine points within `distance` of a query polygon, which may be a
    /// MultiPolygon. The query is given as its own ring arrays (exterior first, then
    /// holes per part) plus poly_offsets grouping rings into parts. Point datasets only.
    fn points_within_distance_of_polygon<'py>(
        &mut self,
        py: Python<'py>,
        poly_xs: PyReadonlyArray1<f64>,
        poly_ys: PyReadonlyArray1<f64>,
        poly_ring_offsets: PyReadonlyArray1<i64>,
        poly_offsets: PyReadonlyArray1<i64>,
        distance: f64,
    ) -> PyResult<Bound<'py, PyArray1<u64>>> {
        if self.ring_offsets.is_some() {
            return Err(PyValueError::new_err(
                "points_within_distance_of_polygon requires a point dataset",
            ));
        }
        let pxs = poly_xs
            .as_slice()
            .map_err(|_| PyValueError::new_err("poly_xs must be a contiguous float64 array"))?;
        let pys = poly_ys
            .as_slice()
            .map_err(|_| PyValueError::new_err("poly_ys must be a contiguous float64 array"))?;
        let pring = poly_ring_offsets
            .as_slice()
            .map_err(|_| PyValueError::new_err("poly_ring_offsets must be contiguous int64"))?;
        let ppoly = poly_offsets
            .as_slice()
            .map_err(|_| PyValueError::new_err("poly_offsets must be contiguous int64"))?;
        if pxs.len() != pys.len() {
            return Err(PyValueError::new_err(
                "poly_xs and poly_ys must have the same length",
            ));
        }
        let candidate = rtree_candidate(&self.stats);
        let bbox = Rect::new(
            coord! { x: 0.0, y: 0.0 },
            coord! { x: 2.0 * distance, y: 2.0 * distance },
        );
        let kind = self.plan_index_kind(&Query::Range { bbox }, 1, candidate);
        self.build_index_if_needed(kind);
        let pts = match kind {
            IndexKind::BruteForce => par_points_within_distance_of_polygon(
                self.brute.as_ref().unwrap(),
                &self.xs,
                &self.ys,
                pxs,
                pys,
                pring,
                ppoly,
                distance,
            ),
            _ => par_points_within_distance_of_polygon(
                self.rtree.as_ref().unwrap(),
                &self.xs,
                &self.ys,
                pxs,
                pys,
                pring,
                ppoly,
                distance,
            ),
        };
        Ok(PyArray1::from_vec(py, pts))
    }

    /// Area of the convex hull of a standalone set of points. Used for grouped
    /// aggregations where the points are not part of any Engine dataset.
    #[staticmethod]
    fn convex_hull_area_of(xs: PyReadonlyArray1<f64>, ys: PyReadonlyArray1<f64>) -> PyResult<f64> {
        let xs_sl = xs
            .as_slice()
            .map_err(|_| PyValueError::new_err("xs must be a contiguous float64 array"))?;
        let ys_sl = ys
            .as_slice()
            .map_err(|_| PyValueError::new_err("ys must be a contiguous float64 array"))?;
        if xs_sl.len() != ys_sl.len() {
            return Err(PyValueError::new_err("xs and ys must have the same length"));
        }
        Ok(convex_hull_area(xs_sl, ys_sl))
    }

    /// Convex hull area for each group defined by CSR offsets over flat xs/ys arrays
    #[staticmethod]
    fn group_convex_hull_areas(
        py: Python<'_>,
        xs: PyReadonlyArray1<f64>,
        ys: PyReadonlyArray1<f64>,
        offsets: PyReadonlyArray1<i64>,
    ) -> PyResult<Py<PyArray1<f64>>> {
        let xs = xs
            .as_slice()
            .map_err(|_| PyValueError::new_err("xs must be a contiguous float64 array"))?;
        let ys = ys
            .as_slice()
            .map_err(|_| PyValueError::new_err("ys must be a contiguous float64 array"))?;
        let offs = offsets
            .as_slice()
            .map_err(|_| PyValueError::new_err("offsets must be a contiguous int64 array"))?;
        let n = offs.len().saturating_sub(1);
        let areas: Vec<f64> = (0..n)
            .into_par_iter()
            .map(|i| {
                let s = offs[i] as usize;
                let e = offs[i + 1] as usize;
                convex_hull_area(&xs[s..e], &ys[s..e])
            })
            .collect();
        Ok(PyArray1::from_vec(py, areas).into())
    }

    /// Euclidean distance between two point sets given as four flat coordinate arrays
    #[staticmethod]
    fn euclidean_distance(
        py: Python<'_>,
        xs1: PyReadonlyArray1<f64>,
        ys1: PyReadonlyArray1<f64>,
        xs2: PyReadonlyArray1<f64>,
        ys2: PyReadonlyArray1<f64>,
    ) -> PyResult<Py<PyArray1<f64>>> {
        let xs1 = xs1
            .as_slice()
            .map_err(|_| PyValueError::new_err("xs1 must be a contiguous float64 array"))?;
        let ys1 = ys1
            .as_slice()
            .map_err(|_| PyValueError::new_err("ys1 must be a contiguous float64 array"))?;
        let xs2 = xs2
            .as_slice()
            .map_err(|_| PyValueError::new_err("xs2 must be a contiguous float64 array"))?;
        let ys2 = ys2
            .as_slice()
            .map_err(|_| PyValueError::new_err("ys2 must be a contiguous float64 array"))?;
        let n = xs1.len();
        let dists: Vec<f64> = (0..n)
            .into_par_iter()
            .map(|i| {
                let dx = xs1[i] - xs2[i];
                let dy = ys1[i] - ys2[i];
                (dx * dx + dy * dy).sqrt()
            })
            .collect();
        Ok(PyArray1::from_vec(py, dists).into())
    }

    /// Heap bytes of all currently-built indexes (excludes the always-present xs/ys arrays).
    /// 0 if none built. Sums every built index. Usually one but several can coexist.
    fn index_bytes(&self) -> usize {
        let mut total = 0;
        if let Some(ref b) = self.brute {
            total += b.heap_bytes();
        }
        if let Some(ref r) = self.rtree {
            total += r.heap_bytes();
        }
        if let Some(ref k) = self.kdtree {
            total += k.heap_bytes();
        }
        if let Some(ref g) = self.grid {
            total += g.heap_bytes();
        }
        total
    }

    /// Number of geometries in the dataset
    fn n(&self) -> usize {
        self.stats.n
    }

    /// Bounding extent of the dataset as (min_x, min_y, max_x, max_y), or None if empty
    fn extent(&self) -> Option<(f64, f64, f64, f64)> {
        self.stats
            .extent
            .map(|r| (r.min().x, r.min().y, r.max().x, r.max().y))
    }

    fn __repr__(&self) -> String {
        format!(
            "Engine(n={}, kind={:?}, dist={:?})",
            self.stats.n, self.stats.kind, self.stats.distribution
        )
    }

    /// Human-readable summary of dataset statistics for debugging
    fn stats_info(&self) -> String {
        format!(
            "n={}, kind={:?}, distribution={:?}, density={:.3e}, extent={:?}",
            self.stats.n,
            self.stats.kind,
            self.stats.distribution,
            self.stats.mean_density,
            self.stats.extent,
        )
    }
}

#[pymodule]
fn _core(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<Engine>()?;
    Ok(())
}
